### ISSUE TITLE
DNS resolver should try each server in /etc/resolv.conf

### ISSUE THREAD

**Issue by emersion** [Luminarys/synapse#110]
Right now it only tries to connect to the first one, and hard fails if the first one doesn't work.

See https://github.com/Luminarys/synapse/blob/master/adns/src/lib.rs#L74

**Comment by Luminarys** [comment]
I'm altering the DNS resolver so that it tries servers sequentially (and A/AAAA in sequence) if DNS fails to resolve for one, however the behavior of trying to force a different resolution to occur if the IP address returned can't be connected to isn't something that I'll be doing (for now at least).

**Comment by emersion** [comment]
Yeah, I don't expect a non-existing domain name to trigger a DNS server change. The resolver should only try another DNS server if it can't _connect_ to one.
