### ISSUE TITLE
Audit memory usage

### ISSUE THREAD

**Issue by ddevault** [Luminarys/synapse#80]

**Comment by Luminarys** [comment]
It's worth nothing that when this issue was made, mmap was being counted as part of memory usage (which is obviously not too accurate).

Memory usage still isn't ideal since we duplicate data structures to make some aspects of RPC more sane, but at this point is reasonable enough. I plan on doing a detailed analysis of this later on and am closing this issue.

To give a very rough statistic now, I'm seeing about 200 MBs of memory usage for 13 MBs of raw torrent files. This can be compared similarly to rtorrent, which uses about 120 MBs of memory for 12 MBs of raw torrent files. Most of the extra size comes from the previously mentioned duplication, and I think this is well within the realm of "acceptable", though still far from ideal.
